### ISSUE TITLE
gradejs.com is protected by password

### ISSUE THREAD

**Issue by kubk** [fingerprintjs/gradejs#7]
The README describes how to use the project: 

https://github.com/fingerprintjs/gradejs/blob/55228c51c460716eb7824f2672868d7918e3d8c9/README.md?plain=1#L7-L8

But currently the website requires a password to enter: https://gradejs.com/

It's not clear how to test the project then.

**Comment by spalt08** [comment]
Hi kubk,

Sorry for the inconvenience. The password is: `gradejs`

We are in the middle of the beta release so any feedback would be helpful!

**Comment by makma** [comment]
@spalt08 shouldn't we mention the pw in the readme? Or remove it completely?

**Comment by spalt08** [comment]
@makma we will soon. I'm working on the new documentation currently :)

**Comment by kubk** [comment]
I am closing the issue since the way to enter the website is documented, thanks 👍
